### ISSUE TITLE
Sircl breaks Jquery load method (I think)

### ISSUE THREAD

**Issue by Cessquill** [codetuner/Sircl2#4] opened 2024-06-12 15:55 UTC
I've added Sircl 2.5.1 to a site that has jquery 3.7.1 and bootstrap 5.3.3

Where I've used Jquery's load shorthand method to populate some html, any data I send with it is stripped out.  However, if I switch to using Jquery's get method, it works again.  As an example (tidied for demonstration)...

`var thisChar = "A";`
`$('#companies').load( 'company-list.asp', { firstChar: thisChar }, function() {`
`	// completed code in here`
`});`

...does not work - the "firstChar" is not received by the ajax page.  However, this...

`var thisChar = "A";`
`$.get( "company-lst.asp", { firstChar: thisChar }, function( companyList ) {`
`	$('#companies').html(companyList);`
`	// completed code here`
`}, "html" );`

...works fine.  I've A/B tested it by removing references to the Sircl js files and the original "load" function works again.  I tested by getting my ajax page to just send back the data it was sent.

It may be me missing something as I'm still getting up to speed on what Sircl can do.  For now I can just remember to use the long hand method.

edit: tidied up markdown code

**Comment by codetuner** [comment] 2024-07-08 10:14
You are correct. Sircl intercepts the jQuery load as well as the jQuery html methods to inject it's behaviour.
It doesn't do that on the jQuery get method.

I was able to reproduce your case and can confirm this is an issue with Sircl. The installation of Sircl should not break your code in this way.

That being said, it looks like what you are doing can be done more "natively" in Sircl, without javascript code. But maybe that is just because you provided a stripped version of the code to reproduce only the issue. It doesn't change the fact that your code should be supported.

There should come soon a fix for this, but I have to check some ins and outs first.

Best regards

**Comment by Cessquill** [comment] 2024-07-08 10:20
Thanks for looking into this.  I'm still looking through Sircl, so may well have missed a better way.  I had removed most of the code for example purposes - there's animation, a loading spinner and conditional scrolling happening.

**Comment by codetuner** [comment] 2024-07-29 17:26
This issue has been resolved in the codebase. The release candidate is now being tested. I'll let you know when a new release is available, that should be in about a week.

**Comment by codetuner** [comment] 2024-07-30 20:38
Hi, release 2.5.5 is been published which contains the fix for your issue.

If you have further questions or want some help or some review, feel free to use the Discussions board. I'll be glad to help!

**Closed by codetuner** 2024-07-30 20:38 UTC
